[colors.primary]
background = '{{colors.surface.default.hex}}'
foreground = '{{colors.on_surface.default.hex}}'

[colors.cursor]
text = '{{colors.on_surface_variant.default.hex}}'
cursor = '{{colors.on_surface.default.hex}}'

[colors.vi_mode_cursor]
text = '{{colors.surface.default.hex}}'
cursor = '{{colors.primary.default.hex}}'

[colors.search.matches]
foreground = '{{colors.on_secondary.default.hex}}'
background = '{{colors.secondary_fixed_dim.default.hex}}'

[colors.search.focused_match]
foreground = '{{colors.on_secondary.default.hex}}'
background = '{{colors.primary.default.hex}}'

[colors.footer_bar]
foreground = '{{colors.on_surface_variant.default.hex}}'
background = '{{colors.surface_bright.default.hex}}'

[colors.hints.start]
foreground = '{{colors.on_surface_variant.default.hex}}'
background = '{{colors.secondary.default.hex}}'

[colors.hints.end]
foreground = '{{colors.on_surface_variant.default.hex}}'
background = '{{colors.secondary.default.hex}}'

[colors.selection]
text = '{{colors.on_secondary.default.hex}}'
background = '{{colors.secondary_fixed_dim.default.hex}}'

[colors.normal]
black   = '{{colors.surface.default.hex}}'
red     = '{{colors.error.default.hex}}'
green   = '{{colors.tertiary.default.hex}}'
yellow  = '{{colors.secondary.default.hex}}'
blue    = '{{colors.primary_container.default.hex | auto_lightness: 20.0}}'
magenta = '{{colors.primary.default.hex}}'
cyan    = '{{colors.secondary_fixed_dim.default.hex | auto_lightness: 20.0}}'
white   = '{{colors.on_surface_variant.default.hex}}'

[colors.bright]
black   = '{{colors.surface_bright.default.hex | auto_lightness: 12.0}}'
red     = '{{colors.error.default.hex}}'
green   = '{{colors.tertiary.default.hex | auto_lightness: 8.0}}'
yellow  = '{{colors.secondary.default.hex | auto_lightness: 8.0}}'
blue    = '{{colors.primary_container.default.hex}}'
magenta = '{{colors.primary.default.hex | auto_lightness: 8.0}}'
cyan    = '{{colors.secondary_fixed_dim.default.hex | auto_lightness: 12.0}}'
white   = '{{colors.on_surface.default.hex}}'

[colors.dim]
black   = '{{colors.surface_container.default.hex}}'
red     = '{{colors.error.default.hex}}'
green   = '{{colors.tertiary.default.hex}}'
yellow  = '{{colors.secondary.default.hex}}'
blue    = '{{colors.primary_container.default.hex}}'
magenta = '{{colors.primary.default.hex}}'
cyan    = '{{colors.secondary_fixed_dim.default.hex}}'
white   = '{{colors.on_surface_variant.default.hex}}'
